# Generated by Django 5.2 on 2025-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_skill_options_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
